#!/usr/bin/env python
# coding: utf-8

# In[1]:


def test():
    print('Test() for function')
    return
test()


# In[4]:


class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()


# In[9]:


class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
print(p1.fact(5))


# In[11]:


import numpy as np
np.arange(1,20)


# In[12]:


np.arange(1,20,5)


# In[23]:


print(np.arange(1,24,4))
np.arange(1,5,2)


# In[17]:


a1=np.array([(1,2,3),(4,5,6)])
print("Slicing column : ",a1[:,1])


# In[18]:


a1=np.array([(1,2,3),(4,5,6)])
print("Slicing column : ",a1[:,2])


# In[21]:


a1=np.array([(1,2,3),(4,5,6)])
print("first row : ",a1[0])


# In[22]:


a1=np.array([(1,2,3),(4,5,6)])
print("second row : ",a1[1])


# In[25]:


a1=np.array([(1,2,3),(4,5,6)])
print(a1)


# In[37]:


a1=np.random.normal(5,1,16)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))


# In[38]:


c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)


# In[41]:


c1=np.array([(1,2),(3,4)])
c1=np.array([(3 ,6),(1,2)])
np.dot(c1,c2)


# In[44]:


import pandas as pd
dict={"name":["anil","akhil","dinesh","harsha","ajay","kranth"],
     "email":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
     "p.no":[2135321525,23601625,36326562536,236262532,6855462322,98754623],
     "address":["gjgfjfgjfg","fgdhhbcbhfghdfh","yityuwrterte","ghdghryjtuitury","wtrqqfwagjty","erythhjktyurgsd"]}
b=pd.DataFrame(dict)
print(b)
                  


# In[46]:


import pandas as pd
dict={"name":["anil","akhil","dinesh","harsha","ajay","kranth"],
    "email.Id":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
                 "p.no":[686535498,25775418,71745,5419814,1472285,58255],
                 "address":["gfhscj","nfgths","ftgggfj","wnjhr","dgjtydt","bgffhhfgc"]}
b=pd.DataFrame(dict)
print(b)


# In[ ]:




